
INSERT INTO toDo(IMPORTANCE,TASK,ISCOMPLETE)
VALUES(1, 'do dishes',0);

INSERT INTO toDo(IMPORTANCE,TASK,ISCOMPLETE)
VALUES(2, 'mow lawn',0);

INSERT INTO toDo(IMPORTANCE,TASK,ISCOMPLETE)
VALUES(3, 'poop',1);

INSERT INTO toDo(IMPORTANCE,TASK,ISCOMPLETE)
VALUES(4, 'eat poop',0);

SELECT * from toDo;
